# Generated by Django 3.2 on 2022-03-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('ONLINE_SERVICES', 'ONLINE_SERVICES_HUMAN_READABLE_FIELD'), ('TRAVEL', 'TRAVEL_HUMAN_READABLE_FIELD'), ('FOOD', 'FOOD_HUMAN_READABLE_FIELD'), ('RENT', 'RENT_HUMAN_READABLE_FIELD'), ('OTHERS', 'OTHERS_HUMAN_READABLE_FIELD')], max_length=255),
        ),
    ]
